In [23]:
import numpy as np

In [24]:
y_predicted = np.array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0])
y_true = np.array([0.2, 0.4, 0.9, 0.1, 0.6, 0.8, 0.3, 0.7, 0.5, 0.2])

In [25]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [26]:
mae(y_predicted, y_true)

Total error is: 3.7
Mean absolute error is: 0.37


np.float64(0.37)

In [27]:
np.abs(y_predicted-y_true)

array([0.2, 0.4, 0.1, 0.9, 0.6, 0.2, 0.3, 0.3, 0.5, 0.2])

In [28]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.37)

In [29]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [30]:
mae_np(y_predicted, y_true)

np.float64(0.37)

In [31]:
np.log([0])

<ipython-input-31-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [32]:
epsilon = 1e-15

In [33]:
np.log([1e-15])

array([-34.53877639])

In [34]:
y_predicted

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0])

In [35]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1e-15,
 1e-15,
 np.int64(1),
 np.int64(1),
 1e-15,
 np.int64(1),
 1e-15,
 np.int64(1),
 np.int64(1),
 1e-15]

In [36]:
1-epsilon

0.999999999999999

In [37]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[1e-15,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15,
 0.999999999999999,
 1e-15,
 0.999999999999999,
 0.999999999999999,
 1e-15]

In [38]:
y_predicted_new = np.array(y_predicted_new)

In [39]:
np.log(y_predicted_new)

array([-3.45387764e+01, -3.45387764e+01, -9.99200722e-16, -9.99200722e-16,
       -3.45387764e+01, -9.99200722e-16, -3.45387764e+01, -9.99200722e-16,
       -9.99200722e-16, -3.45387764e+01])

In [40]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(12.779507185602991)

In [41]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [42]:
log_loss(y_true, y_predicted)

np.float64(12.779507185602991)

In [43]:
#Without Numpy
def mse(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += (yp - yt) ** 2
    mse_value = total_error / len(y_predicted)
    return mse_value

print(mse(y_predicted, y_true))

0.189


In [44]:
#With Numpy
def mse_np(y_predicted, y_true):
    return np.mean((y_predicted - y_true) ** 2)

print(mse_np(y_predicted, y_true))

0.189
